# Generated by Django 3.0.7 on 2020-10-08 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Entertainment',
        ),
    ]
