# Generated by Django 3.0.7 on 2020-10-08 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_business_celebrities_fieldslist_health_technology'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fieldsList',
            new_name='Life_style',
        ),
    ]
