# Generated by Django 3.0.7 on 2020-10-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20201007_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='post_banner',
            field=models.FileField(blank=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='celebrities',
            name='post_banner',
            field=models.FileField(blank=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='entertainment',
            name='post_banner',
            field=models.FileField(blank=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='health',
            name='post_banner',
            field=models.FileField(blank=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='life_style',
            name='post_banner',
            field=models.FileField(blank=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='sport',
            name='post_banner',
            field=models.FileField(blank=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='technology',
            name='post_banner',
            field=models.FileField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('Business', 'Business'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Life style', 'Life style'), ('Celebrities', 'Celebrities')], default='Business', max_length=50),
        ),
        migrations.AlterField(
            model_name='celebrities',
            name='category',
            field=models.CharField(choices=[('Business', 'Business'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Life style', 'Life style'), ('Celebrities', 'Celebrities')], default='Celebrities', max_length=50),
        ),
        migrations.AlterField(
            model_name='entertainment',
            name='category',
            field=models.CharField(choices=[('Business', 'Business'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Life style', 'Life style'), ('Celebrities', 'Celebrities')], default='Entertainment', max_length=50),
        ),
        migrations.AlterField(
            model_name='health',
            name='category',
            field=models.CharField(choices=[('Business', 'Business'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Life style', 'Life style'), ('Celebrities', 'Celebrities')], default='Health', max_length=50),
        ),
        migrations.AlterField(
            model_name='life_style',
            name='category',
            field=models.CharField(choices=[('Business', 'Business'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Life style', 'Life style'), ('Celebrities', 'Celebrities')], default='Life style', max_length=50),
        ),
        migrations.AlterField(
            model_name='sport',
            name='category',
            field=models.CharField(choices=[('Business', 'Business'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Life style', 'Life style'), ('Celebrities', 'Celebrities')], default='Sports', max_length=50),
        ),
        migrations.AlterField(
            model_name='technology',
            name='category',
            field=models.CharField(choices=[('Business', 'Business'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Life style', 'Life style'), ('Celebrities', 'Celebrities')], default='Technology', max_length=50),
        ),
    ]
