# Generated by Django 3.0.7 on 2020-10-08 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20201007_1747'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Life_style',
            new_name='LifeStyle',
        ),
    ]
