# Generated by Django 3.0.7 on 2020-10-10 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_breaking_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Breaking_news',
            new_name='BreakingNews',
        ),
    ]
