# Generated by Django 3.0.7 on 2020-10-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
